GET http://localhost:3001/api/persons


### get person by api
GET http://localhost:3001/api/persons/100


### DELETE person
DELETE  http://localhost:3001/api/persons/4

### POST person
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "hoangnam123123",
    "number": "0938933822"
}