GET http://localhost:3001/api/persons


### get person by api
GET http://localhost:3001/api/persons/6135f6f172f5eba8e4a0b84a


### DELETE person
DELETE  http://localhost:3001/api/persons/6135ecad70729d714324937d

### POST person
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Vy",
    "number": "093893"
}

### UPDATE person
PUT  http://localhost:3001/api/persons/6135f595e3e2fc915f48c830
Content-Type: application/json

{
    "name": "hnam12341234",
    "number": "0938922222"
}